// Generated by CoffeeScript 1.6.3
(function() {
  var Bug;

  Bug = (function() {
    function Bug(x, y) {
      this.x = x;
      this.y = y;
      this.plane = null;
    }

    Bug.prototype.move = function() {};

    Bug.prototype.getRefPoints = function(x, y, heading) {
      var backAngle, leftAngle, points, rightAngle;
      console.log("Bug heading: " + heading);
      points = {};
      points.front = [x + 5 * Math.cos(this.degreesToRadians(heading)), y + 5 * Math.sin(this.degreesToRadians(heading))];
      rightAngle = this.degreesToRadians(heading - 90);
      points.right = [x + 10 * Math.cos(this.rightAngle), y + 10 * Math.sin(this.rightAngle)];
      backAngle = this.degreesToRadians(heading + 180);
      points.back = [x + 5 * Math.cos(backAngle), y + 5 * Math.sin(backAngle)];
      leftAngle = this.degreesToRadians(heading + 90);
      points.left = [x + 10 * Math.cos(leftAngle), y + 10 * Math.sin(leftAngle)];
      return points;
    };

    Bug.prototype.putInPlane = function(plane) {
      return this.plane = plane;
    };

    Bug.prototype.degreesToRadians = function(degs) {
      return degs * (Math.PI / 180);
    };

    Bug.prototype.radiansToDegrees = function(rads) {
      return rads * (180 / Math.PI);
    };

    return Bug;

  })();

  this.Bug = Bug;

}).call(this);
