// Generated by CoffeeScript 1.6.3
(function() {
  var Plane;

  Plane = (function() {
    function Plane(svg, sizeX, sizeY, width, height) {
      var i, j, toAdd;
      this.svg = svg;
      this.sizeX = sizeX;
      this.sizeY = sizeY;
      this.width = width;
      this.height = height;
      this.EAST = 0;
      this.oldPoint = [];
      this.NORTH = 90;
      this.WEST = 180;
      this.SOUTH = 270;
      this.pts = [];
      i = 0;
      while (i < this.width) {
        j = 0;
        toAdd = [];
        while (j < this.height) {
          toAdd[toAdd.length] = false;
          j++;
        }
        i++;
        this.pts[this.pts.length] = toAdd;
      }
      this.widthX = this.sizeX / this.width;
      this.heightY = this.sizeY / this.height;
      alert("wx: " + this.widthX + " wy: " + this.heightY);
      this.rects = [];
      i = 0;
      while (i < this.width) {
        j = 0;
        toAdd = [];
        while (j < this.height) {
          toAdd[toAdd.length] = this.svg.rect(this.widthX, this.heightY).move(j * this.widthX, i * this.heightY).attr({
            stroke: "black",
            "stroke-width": 0.5,
            fill: "white"
          });
          j++;
        }
        this.rects[this.rects.length] = toAdd;
        i++;
      }
    }

    Plane.prototype.addWall = function(x, y) {
      this.pts[y][x] = true;
      return this.rects[x][y].style("fill", "black");
    };

    Plane.prototype.canMove = function(x, y, dir) {
      var nx, ny;
      if (dir === this.EAST) {
        nx = x + 1;
        ny = y;
      } else if (dir === this.NORTH) {
        nx = x;
        ny = y - 1;
      } else if (dir === this.WEST) {
        nx = x - 1;
        ny = y;
      } else if (dir === this.SOUTH) {
        nx = x;
        nx = y + 1;
      }
      return !(this.pts[ny][nx] === true);
    };

    Plane.prototype.drawPoint = function(x, y) {
      return this.rects[y][x].style("fill", "green");
    };

    Plane.prototype.clearPoint = function(x, y) {
      return this.rects[y][x].style("fill", "white");
    };

    return Plane;

  })();

  this.Plane = Plane;

}).call(this);
