// Generated by CoffeeScript 1.6.3
(function() {
  var Plane;

  Plane = (function() {
    function Plane(svg, sizeX, sizeY, width, height) {
      var i, j, toAdd;
      this.svg = svg;
      this.sizeX = sizeX;
      this.sizeY = sizeY;
      this.width = width;
      this.height = height;
      this.EAST = 0;
      this.NORTH = 90;
      this.WEST = 180;
      this.SOUTH = 270;
      this.firstLap = true;
      this.pts = [];
      i = 0;
      while (i < this.width) {
        j = 0;
        toAdd = [];
        while (j < this.height) {
          toAdd[toAdd.length] = false;
          j++;
        }
        i++;
        this.pts[this.pts.length] = toAdd;
      }
      this.widthX = this.sizeX / this.width;
      this.heightY = this.sizeY / this.height;
      alert("wx: " + this.widthX + " wy: " + this.heightY);
      this.rects = [];
      if (this.svg !== null) {
        i = 0;
        while (i < this.width) {
          j = 0;
          toAdd = [];
          while (j < this.height) {
            toAdd[toAdd.length] = this.svg.rect(this.widthX, this.heightY).move(j * this.widthX, i * this.heightY).attr({
              stroke: "black",
              "stroke-width": 0.5,
              fill: "white"
            });
            j++;
          }
          this.rects[this.rects.length] = toAdd;
          i++;
        }
      }
    }

    Plane.prototype.addWall = function(x, y) {
      this.pts[y][x] = true;
      if (this.svg !== null) {
        return this.rects[y][x].style("fill", "black");
      }
    };

    Plane.prototype.canMove = function(x, y, dir) {
      var nx, ny;
      if (dir === this.EAST) {
        nx = x + 1;
        ny = y;
      } else if (dir === this.NORTH) {
        nx = x;
        ny = y - 1;
      } else if (dir === this.WEST) {
        nx = x - 1;
        ny = y;
      } else if (dir === this.SOUTH) {
        nx = x;
        ny = y + 1;
      }
      if (ny >= this.height || nx >= this.width) {
        return false;
      } else {
        return !this.pts[ny][nx];
      }
    };

    Plane.prototype.drawPoint = function(x, y) {
      return this.drawPointCol(x, y, "green");
    };

    Plane.prototype.drawPointCol = function(x, y, color) {
      if (this.svg !== null) {
        return this.rects[y][x].style("fill", color);
      }
    };

    Plane.prototype.clearPoint = function(x, y) {
      if (this.svg !== null) {
        return this.rects[y][x].style("fill", "white");
      }
    };

    return Plane;

  })();

  this.Plane = Plane;

}).call(this);
